engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - app/**
  - "**.js"
