engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
